/*
 * Copyright 2026 Daniel Abbati and the loxmq contributors
 * SPDX-License-Identifier: Apache-2.0
 */

package com.quaddan.iot.loxmq.transport;

import com.hivemq.client.mqtt.MqttGlobalPublishFilter;
import com.hivemq.client.mqtt.mqtt5.Mqtt5BlockingClient;
import com.hivemq.client.mqtt.mqtt5.Mqtt5Client;
import com.hivemq.client.mqtt.mqtt5.message.publish.Mqtt5Publish;
import com.quaddan.iot.loxmq.testresources.FakeMiniserverFullResource;
import com.quaddan.iot.loxmq.testresources.MosquittoTestResource;
import io.quarkus.test.common.QuarkusTestResource;
import io.quarkus.test.junit.QuarkusIntegrationTest;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.TimeUnit;

import static io.restassured.RestAssured.given;
import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.equalTo;

/**
 * Crypto round-trip IT — covers the 🟢 "Validation crypto round-trip dans IT"
 * TODO item. The {@code LoxoneCryptoService} is well unit-tested in
 * isolation; this IT asserts that what the binding actually sends over
 * the WebSocket can be decrypted by something that holds the matching
 * keypair / session key. A drift on either side (algorithm name, padding
 * mode, salt-preamble shape, IV layout in the RSA-wrapped envelope)
 * would otherwise go undetected.
 *
 * <h3>Two assertions in one round-trip</h3>
 *
 * <ol>
 *   <li><b>Handshake getjwt</b> — after {@code /api/v1/connect} returns
 *       RUNNING, the fake has RSA-unwrapped the AES session key the
 *       binding generated, AES-decrypted the first
 *       {@code jdev/sys/enc/…} frame, and pushed the cleartext into
 *       {@link FakeMiniserverFullResource#decryptedCommands()}. We
 *       assert this first entry starts with {@code "getjwt/"} —
 *       confirms the keyexchange envelope (HEX(aesKey):HEX(iv) wrapped
 *       with RSA/ECB/PKCS1Padding) round-trips correctly.</li>
 *
 *   <li><b>MQTT-driven command</b> — we then publish a command on
 *       {@code …/command}, wait for the orchestrator to emit the
 *       encrypted text frame, and assert the fake decrypts it to
 *       {@code "jdev/sps/io/{uuid}/{cmd}"}. Confirms post-handshake
 *       AES-CBC + salt-rotation behaves correctly through the full
 *       CDI event chain.</li>
 * </ol>
 *
 * <h3>Why decryption on the fake side (vs. asserting ciphertext bytes)</h3>
 * Asserting ciphertext bytes would need a fixed seed for both the AES
 * key, the IV, and the salt — all generated by {@code SecureRandom} in
 * the production crypto service. We don't want test-only hooks to
 * inject fixed entropy (that's a real attack surface). Decrypting on
 * the fake side using the matching keypair / session key is the
 * production-shape test: we exercise exactly the path a real Miniserver
 * would, with random entropy on both sides.
 *
 * <h3>What this catches that {@code LoxoneCryptoServiceTest} can't</h3>
 * <ul>
 *   <li>RSA padding mode + AES transformation drift between the binding
 *       config and the actual JCE cipher names. Unit tests use the same
 *       config; here the fake hardcodes {@code RSA/ECB/PKCS1Padding} +
 *       {@code AES/CBC/PKCS5Padding} — a drift would surface as
 *       BadPaddingException on the fake side.</li>
 *   <li>The order in which the binding sends key components in the
 *       wrapped envelope ({@code HEX(key):HEX(iv)}, not the reverse) —
 *       a bug here would produce nonsense on AES decrypt.</li>
 *   <li>Salt-preamble shape ({@code salt/<hex>/<command>\0} vs the
 *       {@code nextSalt/<prev>/<new>/<command>\0} variant) — the fake
 *       strips both, so any drift surfaces as a leftover preamble in
 *       the decrypted command, easy to spot on the IT assertion.</li>
 * </ul>
 *
 * <h3>What this still doesn't cover</h3>
 * Salt rotation between two post-RUNNING commands (would need to drive
 * the binding past its salt-max-age window — currently 1 h default,
 * impractical for an IT). Unit-tested via
 * {@code LoxoneCryptoServiceTest#wrapCommand_RotatesSaltAfterMaxAge}.
 */
@QuarkusIntegrationTest
@QuarkusTestResource( value = MosquittoTestResource.class, restrictToAnnotatedClass = true )
@QuarkusTestResource( value = FakeMiniserverFullResource.class, restrictToAnnotatedClass = true )
@DisplayName( "CryptoRoundTripIT — getjwt + MQTT command decrypt cleanly on the fake side" )
class CryptoRoundTripIT
{
    private static final String APP_ID         = "7b66ce4a-c00a-453c-8da3-314e971db14d";
    private static final String COMMAND_TOPIC  = "iot/loxmq/" + APP_ID + "/command";
    private static final String CMD_RESP_TOPIC = "iot/loxmq/" + APP_ID + "/command_response";

    /** A UUID + command pair distinct enough to spot in the decrypt log
     *  if the assertion ever fails. The literal substrings are checked
     *  directly against the decrypted command line. */
    private static final String TEST_CMD_UUID = "crypto-it-uuid-cafef00d";
    private static final String TEST_CMD_VERB = "test-verb-on";

    private Mqtt5BlockingClient observer;

    @BeforeEach
    void connectObserver()
    {
        observer = Mqtt5Client.builder()
                              .identifier( "crypto-it-observer-" + UUID.randomUUID() )
                              .serverHost( MosquittoTestResource.brokerHost() )
                              .serverPort( MosquittoTestResource.brokerPort() )
                              .buildBlocking();
        observer.connect();
    }

    @AfterEach
    void disconnectObserver()
    {
        if ( observer != null )
        {
            try { observer.disconnect(); } catch ( Exception ignored ) { /* best-effort */ }
            observer = null;
        }
    }

    @Test
    @DisplayName( "fake unwraps RSA session key → AES-decrypts getjwt + MQTT command" )
    void cryptoRoundTrip() throws Exception
    {
        try ( Mqtt5BlockingClient.Mqtt5Publishes pubs =
                      observer.publishes( MqttGlobalPublishFilter.SUBSCRIBED ) )
        {
            observer.subscribeWith().topicFilter( CMD_RESP_TOPIC ).send();

            // 1. Transport up → MQTT client connects to Mosquitto.
            given().when()
                   .post( "/api/v1/transport/connect" )
                   .then()
                   .statusCode( 200 )
                   .body( "status", equalTo( "connected" ) );

            // 2. Bootstrap → fake hands the binding its RSA public key. The
            //    fake KEEPS the matching private key for the decrypt path.
            given().when()
                   .post( "/api/v1/bootstrap" )
                   .then()
                   .statusCode( 200 )
                   .body( "status", equalTo( "success" ) );

            // 3. Connect → WS handshake runs. First WS text frame is
            //    `jdev/sys/keyexchange/{base64}` — the fake RSA-decrypts
            //    it to recover HEX(aesKey):HEX(iv). Subsequent
            //    `jdev/sys/enc/…` frames are AES-decrypted; the first one
            //    is the encrypted getjwt request.
            given().when()
                   .post( "/api/v1/connect" )
                   .then()
                   .statusCode( 200 )
                   .body( "state", equalTo( "RUNNING" ) );

            // 4. Assert the getjwt round-trip. By the time /connect
            //    returns RUNNING the orchestrator has sent (and the fake
            //    has decrypted) at least the getjwt frame.
            List< String > afterHandshake = FakeMiniserverFullResource.decryptedCommands();
            assertThat( afterHandshake )
                    .as( "fake must have decrypted at least the getjwt frame after RUNNING" )
                    .isNotEmpty();
            assertThat( afterHandshake.get( 0 ) )
                    .as( "first decrypted frame is the handshake's getjwt — shape per protocol §Authentication" )
                    .startsWith( "jdev/sys/getjwt/" );

            // 5. Drive an MQTT command. CommandSubscriber.onMessage parses
            //    the JSON, fires MiniserverCommandEvent, the orchestrator
            //    encrypts `jdev/sps/io/{uuid}/{cmd}` and sends it. The fake
            //    decrypts and appends to decryptedCommands.
            String payload = "{\"uuid\":\"" + TEST_CMD_UUID + "\",\"command\":\"" + TEST_CMD_VERB + "\"}";
            observer.publishWith()
                    .topic( COMMAND_TOPIC )
                    .payload( payload.getBytes( StandardCharsets.UTF_8 ) )
                    .send();

            // 6. Wait for the command-response on MQTT — confirms the
            //    orchestrator's encrypted send + the fake's reply round-
            //    trip completed. By this point the decryptedCommands list
            //    is guaranteed to contain the new entry (the fake decrypts
            //    BEFORE sending the reply).
            Optional< Mqtt5Publish > resp = pubs.receive( 10, TimeUnit.SECONDS );
            assertThat( resp )
                    .as( "command-response on %s within 10s of publishing on %s",
                         CMD_RESP_TOPIC, COMMAND_TOPIC )
                    .isPresent();

            // 7. Assert the post-RUNNING command decrypted to exactly the
            //    expected `jdev/sps/io/{uuid}/{cmd}` shape.
            List< String > afterCommand = FakeMiniserverFullResource.decryptedCommands();
            assertThat( afterCommand )
                    .as( "decryptedCommands must have grown by one (handshake + 1 post-RUNNING)" )
                    .hasSizeGreaterThanOrEqualTo( afterHandshake.size() + 1 );
            String lastDecrypted = afterCommand.get( afterCommand.size() - 1 );
            assertThat( lastDecrypted )
                    .as( "post-RUNNING decrypted command shape — full plaintext that the orchestrator sent" )
                    .isEqualTo( "jdev/sps/io/" + TEST_CMD_UUID + "/" + TEST_CMD_VERB );
        }
    }
}
