/*
 * Copyright 2026 Daniel Abbati and the loxmq contributors
 * SPDX-License-Identifier: Apache-2.0
 */

package com.quaddan.iot.loxmq.util.logging;

import io.quarkus.runtime.annotations.RegisterForReflection;

/**
 * Native-image reflection hints for {@link LoggingProducers}.
 *
 * <h3>Why a separate class</h3>
 * {@link RegisterForReflection} isn't @Repeatable. The DTO catalog in
 * {@code NativeReflectionConfig} already carries one
 * {@code @RegisterForReflection(targets = …)}. The logging classes use
 * {@code classNames = …} (because the JBoss LogManager types aren't
 * transitively importable from our package without dragging in module
 * exports) and need {@code methods/fields = true} — that's a second
 * annotation. Per-concern config classes is the cleanest pattern.
 *
 * <h3>What's covered + why</h3>
 * {@code LoggingProducers.walk} walks the root logger's handler tree
 * at {@code @PostConstruct} time using reflection on TWO axes :
 *
 * <ol>
 *   <li><b>Method reflection</b> —
 *       {@code handler.getClass().getMethod("getHandlers").invoke(handler)}
 *       to reach children of {@code ExtHandler} subclasses
 *       ({@code DelayedHandler}, {@code QuarkusDelayedHandler}, etc.),
 *       and {@code getMethod("getFile").invoke(handler)} on the
 *       {@code FileHandler} subtree to locate {@code warn.log} (strict-WARN
 *       filter install). Without {@code methods = true}, the native image
 *       strips method metadata → {@code NoSuchMethodException} → silent
 *       recursion short-circuit / handler not found.</li>
 *   <li><b>Field reflection</b> — {@code cls.getDeclaredFields()} +
 *       {@code f.get(handler)} to reach the real {@code ConsoleHandler}
 *       wrapped inside Quarkus's anonymous wrappers (via the synthetic
 *       {@code val$delegate} field generated by javac on
 *       {@code LoggingSetupRecorder}'s lambda captures). Without
 *       {@code fields = true}, the native image strips field metadata
 *       → empty {@code getDeclaredFields()} → recursion never reaches
 *       the wrapped handler.</li>
 * </ol>
 *
 * <p>Without these hints, the WARN
 * {@code "No ConsoleHandler found on the root logger —
 * LoxmqConsoleFormatter not installed"} appears at every native
 * boot, Quarkus's default formatter takes over, and the operator
 * sees plain pattern logs instead of the coloured output with
 * per-level emojis.
 *
 * <h3>Limits of this fix</h3>
 * We register the <i>stable</i> handler classes by name. We can't
 * register the <i>anonymous</i> wrapper classes generated by
 * {@code LoggingSetupRecorder} — their names (e.g.
 * {@code LoggingSetupRecorder$$Lambda$N} or
 * {@code LoggingSetupRecorder$0}) depend on javac/JDK version and
 * change across builds.
 *
 * <p>In practice this is fine because the wrappers only appear in
 * Quarkus DEV mode (lambda-based runtime setup). NATIVE mode's
 * Quarkus build-time logging recorder produces simpler tree layouts
 * — the {@code getHandlers()} recursion reaches the
 * {@code ConsoleHandler} directly without needing to traverse the
 * synthetic field of an anonymous wrapper.
 *
 * <h3>Verification</h3>
 * Build native, run the binary, grep the boot log :
 * <pre>
 *   mvn package -Pnative -Dquarkus.profile=dev -Dquarkus.native.container-build=true -DskipTests
 *   ./target/loxmq-1.0.0-runner 2&gt;&amp;1 | grep -E "Installed LoxmqConsoleFormatter|No ConsoleHandler found"
 * </pre>
 *
 * Expected with the hints registered:
 * <pre>
 *   ✅ Installed LoxmqConsoleFormatter on 1 console handler (colours + per-level icons active)
 * </pre>
 *
 * @see LoggingProducers
 * @see <a href="https://quarkus.io/guides/writing-native-applications-tips#registerForReflection">
 *      Quarkus — Writing native applications, §RegisterForReflection</a>
 */
@RegisterForReflection(
        classNames = {
                "org.jboss.logmanager.handlers.ConsoleHandler",
                "org.jboss.logmanager.ExtHandler",
                "org.jboss.logmanager.handlers.DelayedHandler",
                "io.quarkus.bootstrap.logging.QuarkusDelayedHandler",
                // FileHandler declares getFile(); SizeRotatingFileHandler is the
                // concrete type Quarkus builds for our size-rotated logs and the
                // type we reflect getFile() on to locate warn.log (strict-WARN
                // filter — see LoggingProducers.installStrictWarnFilter).
                "org.jboss.logmanager.handlers.FileHandler",
                "org.jboss.logmanager.handlers.SizeRotatingFileHandler",
        },
        methods = true,
        fields = true
)
public final class LoggingReflectionConfig
{
    private LoggingReflectionConfig() { }
}
